name: vq
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.12.7=py310h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h7f8727e_2
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1s=h7f8727e_0
  - pip=22.3.1=py310h06a4308_0
  - python=3.10.4=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=65.6.3=py310h06a4308_0
  - sqlite=3.38.5=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2022g=h04d1e81_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - absl-py==1.3.0
    - academictorrents==2.3.3
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - albumentations==1.3.0
    - aniso8601==9.0.1
    - antlr4-python3-runtime==4.9.3
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - astroid==2.14.1
    - asttokens==2.2.1
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - attrs==22.2.0
    - autofaiss==2.15.5
    - backcall==0.2.0
    - beautifulsoup4==4.11.2
    - bencode.py==2.0.0
    - bitstring==3.1.5
    - bleach==6.0.0
    - braceexpand==0.1.7
    - cachetools==5.2.1
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - clip-anytorch==2.5.0
    - clip-retrieval==2.36.1
    - comm==0.1.2
    - contourpy==1.0.6
    - cycler==0.11.0
    - dataclasses==0.6
    - debugpy==1.6.6
    - decorator==5.1.1
    - defusedxml==0.7.1
    - diffusers==0.16.1
    - dill==0.3.6
    - docker-pycreds==0.4.0
    - easydict==1.10
    - einops==0.6.0
    - embedding-reader==1.5.0
    - executing==1.2.0
    - exifread-nocycle==3.0.1
    - faiss-cpu==1.7.3
    - fastjsonschema==2.16.3
    - filelock==3.9.0
    - fire==0.4.0
    - flask==2.2.2
    - flask-cors==3.0.10
    - flask-restful==0.3.9
    - flatbuffers==23.3.3
    - fonttools==4.38.0
    - fqdn==1.5.1
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - ftfy==6.1.1
    - future==0.16.0
    - gast==0.4.0
    - gitdb==4.0.10
    - gitpython==3.1.30
    - google-auth==2.16.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.51.1
    - h5py==3.8.0
    - huggingface-hub==0.14.1
    - idna==3.4
    - imageio==2.25.1
    - img2dataset==1.41.0
    - importlib-metadata==6.6.0
    - ipykernel==6.21.3
    - ipython==8.10.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.4
    - isoduration==20.11.0
    - isort==5.12.0
    - itsdangerous==2.1.2
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-console==6.6.3
    - jupyter-events==0.6.3
    - jupyter_client==8.0.3
    - jupyter_core==5.3.0
    - jupyter_server==2.5.0
    - jupyter_server_terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.5
    - keras==2.11.0
    - kiwisolver==1.4.4
    - kornia==0.6.9
    - lazy-object-proxy==1.9.0
    - libclang==15.0.6.1
    - lmdb==1.4.0
    - lpips==0.1.4
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - matplotlib-inline==0.1.6
    - mccabe==0.7.0
    - mistune==2.0.5
    - multidict==6.0.4
    - multilingual-clip==1.0.10
    - nbclassic==0.5.3
    - nbclient==0.7.2
    - nbconvert==7.2.10
    - nbformat==5.7.3
    - nest-asyncio==1.5.6
    - networkx==3.0
    - nltk==3.8.1
    - notebook==6.5.3
    - notebook_shim==0.2.2
    - numpy==1.24.1
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - open-clip-torch==2.13.0
    - opencv-python==4.7.0.68
    - opencv-python-headless==4.7.0.68
    - opt-einsum==3.3.0
    - packaging==23.0
    - pandas==1.5.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.4.0
    - platformdirs==3.0.0
    - prometheus-client==0.16.0
    - promise==2.3
    - prompt-toolkit==3.0.36
    - protobuf==3.19.6
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==7.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.6
    - pycparser==2.21
    - pydeprecate==0.3.1
    - pygments==2.14.0
    - pylint==2.16.1
    - pyparsing==3.0.9
    - pypubsub==3.3.0
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - python-version==0.0.2
    - pytorch-lightning==1.5.6
    - pytz==2022.7
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==25.0.1
    - qtconsole==5.4.1
    - qtpy==2.3.0
    - qudida==0.0.4
    - regex==2022.10.31
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rsa==4.9
    - scikit-image==0.19.3
    - scikit-learn==1.2.1
    - scipy==1.10.0
    - seaborn==0.12.2
    - send2trash==1.8.0
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.97
    - sentry-sdk==1.12.1
    - setproctitle==1.3.2
    - shortuuid==1.0.11
    - six==1.16.0
    - sklearn==0.0.post1
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.4
    - stack-data==0.6.2
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-estimator==2.11.0
    - tensorflow-io-gcs-filesystem==0.31.0
    - termcolor==2.2.0
    - terminado==0.17.1
    - test-tube==0.7.5
    - threadpoolctl==3.1.0
    - tifffile==2023.2.3
    - timm==0.6.12
    - tinycss2==1.2.1
    - tokenizers==0.13.2
    - tomli==2.0.1
    - tomlkit==0.11.6
    - torch==1.13.1
    - torchmetrics==0.11.0
    - torchvision==0.14.1
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.9.0
    - transformers==4.26.1
    - typing_extensions==4.4.0
    - uri-template==1.2.0
    - urllib3==1.26.13
    - wandb==0.12.21
    - wcwidth==0.2.5
    - webcolors==1.12
    - webdataset==0.2.33
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.5
    - wrapt==1.14.1
    - yarl==1.8.2
    - zipp==3.15.0
prefix: /home/huangmq/anaconda3/envs/vq
